added delete vocab route to unification
vlizBE/vocabserver-app pull request #13
Opened 2023-01-09 11:14 UTC by SchrodingersCat00

2023-01-11 10:18 UTC, MikiDi requested changes
Haal je ook nog prefixes weg waar ze niet nodig zijn?

2023-01-11 10:18 UTC, MikiDi commented on services/content-unification/unification.py
> +    ?sourceDataset ?sourceDatasetPred ?sourceDatasetObj
Om consequent te zijn zou ik net zoals in de query  hierboven ook `?vocab ext:sourceDataset ?sourceDataset .` meenemen bij het verwijderen.

2023-01-11 10:18 UTC, MikiDi commented on services/content-unification/unification.py
> +    ?sourceDataset void:classPartition ?classPart .
Deze query en degene hieronder kunnen misschien makkelijk gecombineerd worden tot 1 door de predicaten `void:classPartition` en `void:propertyPartition` deel te binden via een `VALUES` blok?

2023-05-25 07:30 UTC, Milan-VLIZ commented
I suppose this one is good to merge? Or no longer relevant?

2023-06-05 11:51 UTC, SchrodingersCat00 commented
This can and should be merged, this is needed to clean up the downloaded files and other relevant metadata that is created when a vocabulary is added.

2023-06-05 11:54 UTC, SchrodingersCat00 commented
@MikiDi or @Jan-PieterBaert does this need to be expanded for LDES vocabs?

2023-06-05 12:38 UTC, Jan-PieterBaert commented
> @MikiDi or @Jan-PieterBaert does this need to be expanded for LDES vocabs?

@SchrodingersCat00 for LDES the docker container that the `ldes-consumer-manager` created should be destroyed

2023-06-05 13:23 UTC, SchrodingersCat00 commented
Is this something you could implement easily? I have no experience controlling docker via scripting whatsoever

2023-06-05 13:45 UTC, Jan-PieterBaert commented
the consumer manager can list the containers, using the SDK function to kill a container (see https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.kill ) it should be easy to implement

2023-06-20 13:42 UTC, merged